name: Localization issue
description: Localization gets everyone on the same page
labels: ["localization", "triage"]
assignees:
  - l0uisgrange
body:
  - type: markdown
    attributes:
      value: |
        Thank for taking the time to help me translate the app correctly!
  - type: dropdown
    id: language
    attributes:
      label: Language
      description: What language are you using?
      options:
      - English (Default)
      - French
      - Danish
      - German
      - Italian
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Spice are you running?
      options:
        - 1.0.0
        - 0.7.0
        - 0.6.1
        - 0.6.0
        - 0.5.1
        - 0.5.0
        - 0.4.1
        - 0.4.0
        - 0.3.0
        - 0.2.1
        - 0.2.0
        - 0.1.0
    validations:
      required: true
  - type: input
    id: where
    attributes:
      label: Where is the localization problem?
      description: Quickly tell us what part of the application is causing the problem
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: What content was wrong?
      description: Paste here the wrong localized content as seen in the application
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is proper localization?
      description: Write your corrected localization here
    validations:
      required: true
