name: "App Store deployment"
on:
  release:
    types: [published]
    branches: ["main"]
  workflow_dispatch:
    inputs:
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
